Worked on option parsing

diff --git a/bashme b/bashme
--- a/bashme
+++ b/bashme
@@ -29,6 +29,7 @@ declare -ri LL_QUIET=6
 declare -i loglevel=$LL_INFO
 declare logfile="./$(command -p basename "$0").log"
 declare log2file=''
+declare log2std=1
 
 ##
 # Logs a message according to its log level.
@@ -36,8 +37,9 @@ declare log2file=''
 #   BASH_LINENO
 #   FUNCNAME
 #   BASH_SOURCE
-#   EX_OK
+#   LL_ERROR
 #   fnt_reset
+#   log2std
 #   log2file
 #   logfile
 # Arguments:
@@ -49,14 +51,15 @@ declare log2file=''
 #   None
 #
 function log() {
-  local index="${BASH_LINENO[$((${#BASH_LINENO} - 1))]}"
-  local IFS='-'
+  local lineno="${BASH_LINENO[$((${#BASH_LINENO} - 1))]}"
   local location=" ${FUNCNAME[2]}(): "
   local logmsg="$(command -p date '+%Y-%M-%d %H:%m:%S') $3($lineno)$location$4"
-  if (( $2 >= $LL_ERROR )); then
-    command -p echo -e "\033[s$1$logmsg$fnt_reset\033[u\033[1B" >&2
-  else
-    command -p echo -e "\033[s$1$logmsg$fnt_reset\033[u\033[1B"
+  if [[ -n "$log2std" ]]; then
+    if (( $2 >= $LL_ERROR )); then
+      command -p echo -e "$1$logmsg$fnt_reset" >&2
+    else
+      command -p echo -e "$1$logmsg$fnt_reset"
+    fi
   fi
   [[ -n "$log2file" ]] && echo "$logmsg" >> $logfile
   return $EX_OK
@@ -164,6 +167,23 @@ function fatal() {
   return $EX_OK
 }
 
+##
+# A makeshift function to cover logging the access to not yet implemented
+# functionality.
+# Globals:
+#   LL_FATAL
+#   loglevel
+#   fg_red
+# Arguments:
+#   None
+# Returns:
+#   None
+#
+function niy() {
+  fatal "Not implemented yet!"
+  return $EX_OK
+}
+
 
 
 ###############################################################################
@@ -219,7 +239,7 @@ function check_retval() {
       debug "${excode}Invalid argument to exit. exit takes only integer args in the range 0 - 255."
       ;;
     $EX_INT)
-      debug "${excode}Script terminated by Control-C."
+      debug "${excode}Command terminated by Control-C."
       ;;
     $EX_OUTOFRANGE)
       debug "${excode}Exit status out of range. exit takes only integer args in the range 0 - 255."
@@ -296,164 +316,130 @@ readonly fnt_no_strikeout='\033[29m'
 readonly fnt_reset='\033[0m'
 
 ##
-# Prints a color table assuming 16bit colors.
+# Prints a table of all the available formats.
 # Globals:
-#   None
+#   fnt_bold
+#   fnt_dim
+#   fnt_italic
+#   fnt_underline
+#   fnt_blink
+#   fnt_overline
+#   fnt_reverse
+#   fnt_hidden
+#   fnt_strikeout
+#   fnt_no_bold
+#   fnt_no_dim
+#   fnt_no_italic
+#   fnt_no_underline
+#   fnt_no_blink
+#   fnt_no_overline
+#   fnt_no_reverse
+#   fnt_no_hidden
+#   fnt_no_strikeout
+#   fnt_reset
 # Arguments:
 #   None
 # Returns:
 #   None
 #
-function colors_16() {
-  trace 'Printing color16 table.'
-  #Background
-  for clbg in {40..47} {100..107} 49 ; do
-    #Foreground
-    for clfg in {30..37} {90..97} 39 ; do
-      #Formatting
-      for attr in 0 1 2 3 4 5 6 7 8 9 ; do
-        #Print the result
-        command -p echo -en "\e[${attr};${clbg};${clfg}m ^[${attr};${clbg};${clfg}m \e[0m"
-      done
-      command -p echo #Newline
-    done
-  done
+function formatting_test() {
+  trace 'Printing formatting table.'
+  command -p echo -e "Bold:      ${fnt_bold}Bold${fnt_no_bold}.      No Bold${fnt_reset}."
+  command -p echo -e "Dim:       ${fnt_dim}Dim${fnt_no_dim}.       No Dim${fnt_reset}."
+  command -p echo -e "Italic:    ${fnt_italic}Italic${fnt_no_italic}.    No Italic${fnt_reset}."
+  command -p echo -e "Underline: ${fnt_underline}Underline${fnt_no_underline}. No Underline${fnt_reset}."
+  command -p echo -e "Blink:     ${fnt_blink}Blink${fnt_no_blink}.     No Blink${fnt_reset}."
+  command -p echo -e "Overline:  ${fnt_overline}Overline${fnt_no_overline}.  No Overline${fnt_reset}."
+  command -p echo -e "Reverse:   ${fnt_reverse}Reverse${fnt_no_reverse}.   No Reverse${fnt_reset}."
+  command -p echo -e "Hidden:    ${fnt_hidden}Hidden${fnt_no_hidden}.    No Hidden${fnt_reset}."
+  command -p echo -e "Strikeout: ${fnt_strikeout}Strikeout${fnt_no_strikeout}. No Strikeout${fnt_reset}."
   return $EX_OK
 }
-
-
-
-###############################################################################
-#                               OPTION PARSING                                #
-###############################################################################
-# Constants
-readonly DEFAULT_OPTS='hvql:o:'
-
-# Variables
-declare opts="$DEFAULT_OPTS"
 
 ##
-# Parses the specified options from the script arguments.
+# Prints a table of all the available colors.
 # Globals:
-#   opts
-#   DEFAULT_OPTS
+#   fg_default
+#   fg_black
+#   fg_red
+#   fg_green
+#   fg_yellow
+#   fg_blue
+#   fg_magenta
+#   fg_cyan
+#   fg_light_gray
+#   fg_dark_gray
+#   fg_light_red
+#   fg_light_green
+#   fg_light_yellow
+#   fg_light_blue
+#   fg_light_magenta
+#   fg_light_cyan
+#   fg_white
+#   bg_default
+#   bg_black
+#   bg_red
+#   bg_green
+#   bg_yellow
+#   bg_blue
+#   bg_magenta
+#   bg_cyan
+#   bg_light_gray
+#   bg_dark_gray
+#   bg_light_red
+#   bg_light_green
+#   bg_light_yellow
+#   bg_light_blue
+#   bg_light_magenta
+#   bg_light_cyan
+#   bg_white
+#   fnt_reset
 # Arguments:
-#   The script arguments ($@)
+#   None
 # Returns:
 #   None
 #
-function parse_opts() {
-  trace "Parsing options using: '$opts'."
-  if [[ $opts =~ $DEFAULT_OPTS.* ]]; then
-    trace 'Old options preserved'
-    local opts_new="${opts:${#DEFAULT_OPTS}:99}"
-    if [[ -n "$opts_new" ]]; then
-      debug "New options: '$opts_new'"
-    fi
-    while command -p getopts "$opts" opt; do
-      case $opt in
-        h|v|q|l|o)
-          trace "Option '$opt' already handled."
-          ;;
-        *)
-          debug "Checking option '$opt'"
-          if [[ $opts_new =~ $opt ]]; then # Option specified
-            eval "$opt=1"
-            if [[ $opts_new =~ $opt: ]]; then # Argument provided
-              opt_name="$opt"
-              eval "$opt="${OPTARG}""
-              debug "Found option '$opt_name=$opt'."
-            else
-              debug "Found option '$opt'."
-            fi
-          else
-            debug "Couldn't find '$opt' in '$opts_new'."
-            print_help
-            exit $EX_MISSUSE
-          fi
-          ;;
-      esac
-    done
-    shift $((OPTIND-1))
-    trace 'Done parsing arguments.'
-  else
-    trace 'Old options overridden.'
-  fi
+function color_test() {
+  trace 'Printing color table.'
+  command -p echo -e "Foreground:"
+  command -p echo -e  "fg_default:    ${fg_default}fg_default${fnt_reset}"
+  command -p echo -en "fg_black:      ${fg_black}fg_black${fnt_reset}      "
+  command -p echo -e  "fg_dark_gray:     ${fg_dark_gray}fg_dark_gray${fnt_reset}"
+  command -p echo -en "fg_red:        ${fg_red}fg_red${fnt_reset}        "
+  command -p echo -e  "fg_light_red:     ${fg_light_red}fg_light_red${fnt_reset}"
+  command -p echo -en "fg_green:      ${fg_green}fg_green${fnt_reset}      "
+  command -p echo -e  "fg_light_green:   ${fg_light_green}fg_light_green${fnt_reset}"
+  command -p echo -en "fg_yellow:     ${fg_yellow}fg_yellow${fnt_reset}     "
+  command -p echo -e  "fg_light_yellow : ${fg_light_yellow}fg_light_yellow${fnt_reset}"
+  command -p echo -en "fg_blue:       ${fg_blue}fg_blue${fnt_reset}       "
+  command -p echo -e  "fg_light_blue:    ${fg_light_blue}fg_light_blue${fnt_reset}"
+  command -p echo -en "fg_magenta:    ${fg_magenta}fg_magenta${fnt_reset}    "
+  command -p echo -e  "fg_light_magenta: ${fg_light_magenta}fg_light_magenta${fnt_reset}"
+  command -p echo -en "fg_cyan:       ${fg_cyan}fg_cyan${fnt_reset}       "
+  command -p echo -e  "fg_light_cyan:    ${fg_light_cyan}fg_light_cyan${fnt_reset}"
+  command -p echo -en "fg_light_gray: ${fg_light_gray}fg_light_gray${fnt_reset} "
+  command -p echo -e  "fg_white:         ${fg_white}fg_white${fnt_reset}"
+  command -p echo -e "Background:"
+  command -p echo -e  "bg_default:    ${bg_default}bg_default${fnt_reset}"
+  command -p echo -en "bg_black:      ${bg_black}bg_black${fnt_reset}      "
+  command -p echo -e  "bg_dark_gray:     ${bg_dark_gray}bg_dark_gray${fnt_reset}"
+  command -p echo -en "bg_red:        ${bg_red}bg_red${fnt_reset}        "
+  command -p echo -e  "bg_light_red:     ${bg_light_red}bg_light_red${fnt_reset}"
+  command -p echo -en "bg_green:      ${bg_green}bg_green${fnt_reset}      "
+  command -p echo -e  "bg_light_green:   ${bg_light_green}bg_light_green${fnt_reset}"
+  command -p echo -en "bg_yellow:     ${bg_yellow}bg_yellow${fnt_reset}     "
+  command -p echo -e  "bg_light_yellow : ${bg_light_yellow}bg_light_yellow${fnt_reset}"
+  command -p echo -en "bg_blue:       ${bg_blue}bg_blue${fnt_reset}       "
+  command -p echo -e  "bg_light_blue:    ${bg_light_blue}bg_light_blue${fnt_reset}"
+  command -p echo -en "bg_magenta:    ${bg_magenta}bg_magenta${fnt_reset}    "
+  command -p echo -e  "bg_light_magenta: ${bg_light_magenta}bg_light_magenta${fnt_reset}"
+  command -p echo -en "bg_cyan:       ${bg_cyan}bg_cyan${fnt_reset}       "
+  command -p echo -e  "bg_light_cyan:    ${bg_light_cyan}bg_light_cyan${fnt_reset}"
+  command -p echo -en "bg_light_gray: ${bg_light_gray}bg_light_gray${fnt_reset} "
+  command -p echo -e  "bg_white:         ${bg_white}bg_white${fnt_reset}"
   return $EX_OK
 }
 
-function print_help() {
-  echo -n 'Usage: '
-  for syn in "${syntax[@]}"; do
-    echo "$(basename $0) $syn"
-    echo -n '       '
-  done
-  echo -en '\033[7D'
-  echo "$usage"
-  echo
-  for option in "${optArray[@]}"; do
-    get_opt "$option"
-    if [[ -n "$short" ]]; then
-      echo -n "  -$short"
-      if [[ -n "$long" ]]; then
-        echo -n ','
-      else
-        echo -n ' '
-      fi
-    else
-      echo -en '     '
-    fi
-    if [[ -n "$long" ]]; then
-      line=" --$long"
-      if [[ -n "$argument" ]]; then
-        line="$line $argument"
-      fi
-      let "len = $maxlen - ${#line} + 1"
-      echo -en "$line "
-      printf ' %.0s' {1..$len}
-    else
-      printf ' %.0s' {1..$maxlen}
-    fi
-    echo -e "$descr"
-  done
-  return $EX_OK
-}
-
-function setup() {
-  if [[ $opts =~ $DEFAULT_OPTS.* ]]; then
-    # Parsing options early
-    if test_option "$@" 'h'; then 
-      print_help
-      exit $EX_OK
-    fi
-    if test_option "$@" 'q'; then
-      loglevel=$LL_QUIET
-    elif test_option "$@" 'v'; then
-      loglevel=$LL_TRACE
-      debug "Set log level to $loglevel."
-    elif test_option "$@" 'l\ *([0-9]*)'; then
-      loglevel=${BASH_REMATCH[1]}
-    fi
-    if [[ $loglevel -ne $LL_QUIET ]]; then
-      if test_option "$@" 'o\ +([/a-zA-Z0-9\.]+)'; then
-        logfile=${BASH_REMATCH[1]}
-        log2file=1
-      fi
-      debug "Set log level to $loglevel"
-      [[ -n "$log2file" ]] && debug "Set log file to '$logfile'."
-    fi
-    if [[ -z "$trapping" ]]; then
-      trap_signals
-    fi
-  fi
-  parse_opts "$@"
-  return $?
-}
-
-function test_option() {
-  [[ \ $1 =~  \ -[a-zA-Z0-9]*$2 ]] && return $EX_OK;
-  return $EX_ERR;
-}
 
 
 ###############################################################################
@@ -462,7 +448,6 @@ function test_option() {
 # Variables
 declare -a traps=(
   ERR
-  EXIT
   INT
 )
 
@@ -650,27 +635,330 @@ function trap_signals() {
 }
 
 
+
+###############################################################################
+#                               OPTION PARSING                                #
+###############################################################################
+# Variables
+declare -a opts_var=()
+declare -a opts_short=()
+declare -a opts_long=()
+declare -a opts_arg=()
+declare -a opts_help=()
+
+define_opt() {
+  trace "Defining option."
+  opts_var+=("$1")
+  opts_short+=("$2")
+  opts_long+=("$3")
+  opts_arg+=("$4")
+  opts_help+=("$5")
+  debug "Defined option. Short: '$1'. Long: '$2'. Argument: '$3'"
+}
+
+##
+# Parses the specified options from the script arguments.
+# Globals:
+#   None
+# Arguments:
+#   The script arguments ($@)
+# Returns:
+#   None
+#
+function parse_opts() {
+  # Define helper functions
+  function find_matching_opt() {
+    trace "Matching '$opt' against the defined options."
+    for index in "${!opts_short[@]}"; do
+      if [[ $opt =~ ^\s*(${opts_short[$index]}|${opts_long[$index]}) ]]; then
+        trace "Found a match at index '$index'."
+        return $EX_OK
+      fi
+    done
+    trace 'No match found.'
+    return $EX_ERR
+  }
+  function expects_argument() {
+    trace "Checking if '$opt' expects an argument."
+    if [[ -n "${opts_arg[$index]}" ]]; then
+      trace "Argument '${opts_arg[$index]}' expected."
+      return $EX_OK
+    fi
+    trace 'No argument expected.'
+    return $EX_ERR
+  }
+  function set_option_variable() {
+    trace "Set argument for '${opts_var[$index]}'."
+    if [[ ! $opt =~ ^\s*(${opts_short[$index]}|${opts_long[$index]})\s*(.*)$ ]]; then
+      fatal "Could not match '$opt' with the selected option."
+    fi
+    local arg="${BASH_REMATCH[2]}"
+    local var="${opts_var[$index]}"
+    eval "$var="$arg""
+    return $EX_OK
+  }
+
+  # Do it
+  trace "Parsing options."
+  local -a args_old=("$@")
+  local -a args=("$@")
+  local opt
+  for opt in "${args[@]}"; do
+    local -i index
+    find_matching_opt
+    if (( $index >= 0 )); then
+      # Option found
+      if expects_argument; then
+        set_option_variable
+      else
+        niy
+      fi
+    else
+      # Argument found
+      niy
+    fi
+  done
+
+
+  local last_opt_name
+  for opt in "${args[@]}"; do
+    # If the string starts with only one dash/plus, 
+    if [[ $opt =~ ^([^a-zA-Z0-9_\-][^-]).+$ ]]; then
+      debug "Need to split the arguments($opt)."
+      local cur_opt="${BASH_REMATCH[1]}"
+      opt="-${opt:2:${#opt}}"
+      if check_if_arg "$cur_opt"; then
+        # Assign rest of string as argument.
+        if [[ -z "$opt" ]]; then
+          # Argument isn't on this string.
+          local opt_var
+          get_opt_var $opt
+          last_opt_name="$opt_var"
+          continue
+        else
+          niy
+        fi
+      fi
+      while true; do
+        return
+      done
+    fi
+  done
+  return $EX_OK
+
+
+  local IFS=","
+  debug "Arguments supplied: '${args[*]}'" 
+  subtitute_long
+  debug "Arguments after shortening: '${args[*]}'" 
+  local opt
+  while command -p getopts "$opts" opt ${args[@]}; do
+    echo "$opt" $OPTIND $OPTARG
+    debug "Checking option '$opt'"
+    local optname="opt_$opt"
+    eval "$optname=1"
+    if [[ $opts_new =~ $opt: ]]; then # Argument provided
+      eval "$opt="${OPTARG}""
+      debug "Found option '$optname=$opt'."
+    else
+      debug "Found option '$opt'."
+    fi
+  done
+  return $EX_OK
+}
+
+
+function assign_opt_val() {
+  local opt="$1"
+  local val="$2"
+  local -i index
+  if [[ ${#opt} = 2 ]]; then
+    for index in "${!opts_short[@]}"; do
+      if [[ "${opts_short[$index]}" = "$short" ]]; then
+        
+        break
+      fi
+    done
+  else
+    niy
+  fi
+}
+
+function get_opt_var() {
+  opt_var="opt_${${${1/^-/}/^-/}/-/_}"
+}
+
+function check_if_arg() {
+  trace "Check if short option expects an argument or not."
+  local short="$1"
+  for index in "${!opts_short[@]}"; do
+    if [[ "${opts_short[$index]}" = "$short" ]]; then
+      if [[ -n "${opts_arg[$index]}" ]]; then
+        trace "It does expect an argument."
+        return $EX_OK;
+      fi
+      break
+    fi
+  done
+  trace "It does not expect an argument."
+  return $EX_ERR
+}
+
+function parse_single_option() {
+  local flag="$1"
+  local argument="$2"
+  trace "Parsing single option: $1 $2"
+  local -i index
+  if [[ ${#flag} = 1 ]]; then
+    for index in "${!opts_short[@]}"; do
+      if [[ "${opts_short[$index]}" = "$flag" ]]; then
+        return
+      fi
+    done
+  else
+    return
+  fi
+}
+function assign_option() {
+  local -i index="$1"
+  local short="${opts_short[$index]}"
+  local long="${opts_long[$index]}"
+  local argument="$2"
+  if [[ -n "$short" ]]; then
+    local name_short="opt_$short"
+  fi
+}
+
+function subtitute_long() {
+  trace 'Substituting long options to short ones.'
+  local -i index
+  local key
+  for key in "${!option_map[@]}"; do
+    for index in "${!args[@]}"; do
+    local arg="${args[$index]}"
+      if [[ $arg =~ ^--$key(\s.*$|$) ]]; then
+        local shortened="-${option_map[$key]}${BASH_REMATCH[1]}"
+        args[$index]="$shortened"
+        debug "Changed option '$arg' to '$shortened'."
+      fi
+    done
+  done
+  trace 'Done with the substitution.'
+  return $EX_OK
+}
+
+function prefetch_options() {
+  if [[ $opts =~ $DEFAULT_OPTS.* ]]; then
+    # Parsing options early
+    if test_option "$@" 'h'; then 
+      print_help
+      exit $EX_OK
+    fi
+    if test_option "$@" 'q'; then
+      loglevel=$LL_QUIET
+    elif test_option "$@" 'v'; then
+      loglevel=$LL_TRACE
+      debug "Set log level to $loglevel."
+    elif test_option "$@" 'l\ *([0-9]*)'; then
+      loglevel=${BASH_REMATCH[1]}
+    fi
+    if [[ $loglevel -ne $LL_QUIET ]]; then
+      debug "Set log level to $loglevel"
+    fi
+    if [[ -z "$trapping" ]]; then
+      trap_signals
+    fi
+  fi
+  return $EX_OK
+}
+
+##
+# Prints the usage and help text.
+# Globals:
+#   opts
+#   DEFAULT_OPTS
+# Arguments:
+#   The script arguments ($@)
+# Returns:
+#   None
+#
+function print_help() {
+  echo -n 'Usage: '
+  for syn in "${syntax[@]}"; do
+    echo "$(basename $0) $syn"
+    echo -n '       '
+  done
+  echo -en '\033[7D'
+  echo "$usage"
+  echo
+  for option in "${optArray[@]}"; do
+    get_opt "$option"
+    if [[ -n "$short" ]]; then
+      echo -n "  -$short"
+      if [[ -n "$long" ]]; then
+        echo -n ','
+      else
+        echo -n ' '
+      fi
+    else
+      echo -en '     '
+    fi
+    if [[ -n "$long" ]]; then
+      line=" --$long"
+      if [[ -n "$argument" ]]; then
+        line="$line $argument"
+      fi
+      let "len = $maxlen - ${#line} + 1"
+      echo -en "$line "
+      printf ' %.0s' {1..$len}
+    else
+      printf ' %.0s' {1..$maxlen}
+    fi
+    echo -e "$descr"
+  done
+  return $EX_OK
+}
+
+function test_option() {
+  [[ \ $1 =~  \ -[a-zA-Z0-9]*$2 ]] && return $EX_OK;
+  return $EX_ERR;
+}
+
+
+
 ###############################################################################
 #                                     EOF                                     #
 ###############################################################################
 
-# Preamble
-opts="${opts}a:"
+# Setup:
+loglevel=$LL_TRACE
+
+define_opt "_log" "-l" "" "<n>" "Log level <n>."
+define_opt "_help" "-h" "--help" "" "Display this help text."
+define_opt "_ver" "-v" "" "" "Display the version."
+define_opt "_file" "" "--file" "<file>" "Load settings from <file>."
+
 syntax=(
   '[OPTION]...'
   '[OPTION]... [FILE]'
 )
 usage='Remove (unlink) the FILE(s).'
+
+parse_opts "$@"
+echo "_log = $_log"
+exit
+
+# Traps:
 traps=(
-  ERr
-  EXIT
+  ERR
   INT
 )
 sig_err() { exit; }
-sig_exit() { exit; }
 sig_int() { exit; }
-setup "$@"
+trap_signals
 
+color_test
+exit
 # Code
 sig_debug() {
     local -i row="$((${BASH_LINENO[0]} - 3))"
